package com.xiaoyu.mbg.pojo;

public class FilmText {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_text.film_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    private Short filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_text.title
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_text.description
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_text.film_id
     *
     * @return the value of film_text.film_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public Short getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_text.film_id
     *
     * @param filmId the value for film_text.film_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_text.title
     *
     * @return the value of film_text.title
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_text.title
     *
     * @param title the value for film_text.title
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_text.description
     *
     * @return the value of film_text.description
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_text.description
     *
     * @param description the value for film_text.description
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}