package com.xiaoyu.mbg.pojo;

import java.util.Date;

public class Inventory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    private Integer inventoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.film_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    private Short filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.store_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    private Byte storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.last_update
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_id
     *
     * @return the value of inventory.inventory_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public Integer getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_id
     *
     * @param inventoryId the value for inventory.inventory_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.film_id
     *
     * @return the value of inventory.film_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public Short getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.film_id
     *
     * @param filmId the value for inventory.film_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.store_id
     *
     * @return the value of inventory.store_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public Byte getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.store_id
     *
     * @param storeId the value for inventory.store_id
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public void setStoreId(Byte storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.last_update
     *
     * @return the value of inventory.last_update
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.last_update
     *
     * @param lastUpdate the value for inventory.last_update
     *
     * @mbggenerated Mon Mar 06 23:26:25 CET 2023
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}