package com.xiaoyu.mbg.mapper;

import com.xiaoyu.mbg.pojo.FilmCategory;
import com.xiaoyu.mbg.pojo.FilmCategoryExample;
import com.xiaoyu.mbg.pojo.FilmCategoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int countByExample(FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int deleteByExample(FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int deleteByPrimaryKey(FilmCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int insert(FilmCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int insertSelective(FilmCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    List<FilmCategory> selectByExample(FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    FilmCategory selectByPrimaryKey(FilmCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByExampleSelective(@Param("record") FilmCategory record, @Param("example") FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByExample(@Param("record") FilmCategory record, @Param("example") FilmCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByPrimaryKeySelective(FilmCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_category
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByPrimaryKey(FilmCategory record);
}