package com.xiaoyu.mbg.mapper;

import com.xiaoyu.mbg.pojo.FilmText;
import com.xiaoyu.mbg.pojo.FilmTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int countByExample(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int deleteByExample(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int deleteByPrimaryKey(Short filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int insert(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int insertSelective(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    List<FilmText> selectByExampleWithBLOBs(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    List<FilmText> selectByExample(FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    FilmText selectByPrimaryKey(Short filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByExampleSelective(@Param("record") FilmText record, @Param("example") FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByExampleWithBLOBs(@Param("record") FilmText record, @Param("example") FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByExample(@Param("record") FilmText record, @Param("example") FilmTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByPrimaryKeySelective(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByPrimaryKeyWithBLOBs(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    int updateByPrimaryKey(FilmText record);
}