package com.xiaoyu.mbg.pojo;

import java.util.Date;

public class Actor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.actor_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Short actorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.first_name
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.last_name
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.actor_id
     *
     * @return the value of actor.actor_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Short getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.actor_id
     *
     * @param actorId the value for actor.actor_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setActorId(Short actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.first_name
     *
     * @return the value of actor.first_name
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.first_name
     *
     * @param firstName the value for actor.first_name
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.last_name
     *
     * @return the value of actor.last_name
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.last_name
     *
     * @param lastName the value for actor.last_name
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.last_update
     *
     * @return the value of actor.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.last_update
     *
     * @param lastUpdate the value for actor.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public String toString() {
        return "Actor{" +
                "actorId=" + actorId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", lastUpdate=" + lastUpdate +
                '}';
    }
}