package com.xiaoyu.mbg.pojo;

import java.util.Date;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Short cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.country_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Short countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Short getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setCityId(Short cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city
     *
     * @return the value of city.city
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city
     *
     * @param city the value for city.city
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.country_id
     *
     * @return the value of city.country_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Short getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.country_id
     *
     * @param countryId the value for city.country_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setCountryId(Short countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.last_update
     *
     * @return the value of city.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.last_update
     *
     * @param lastUpdate the value for city.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}