package com.xiaoyu.mbg.pojo;

import java.util.Date;

public class Country {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Short countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_id
     *
     * @return the value of country.country_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Short getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_id
     *
     * @param countryId the value for country.country_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setCountryId(Short countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country
     *
     * @return the value of country.country
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country
     *
     * @param country the value for country.country
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.last_update
     *
     * @return the value of country.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.last_update
     *
     * @param lastUpdate the value for country.last_update
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}