package com.xiaoyu.mbg.pojo;

public class FilmCategoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_category.film_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Short filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_category.category_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    private Byte categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_category.film_id
     *
     * @return the value of film_category.film_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Short getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_category.film_id
     *
     * @param filmId the value for film_category.film_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setFilmId(Short filmId) {
        this.filmId = filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_category.category_id
     *
     * @return the value of film_category.category_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public Byte getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_category.category_id
     *
     * @param categoryId the value for film_category.category_id
     *
     * @mbggenerated Tue Mar 07 11:48:05 CET 2023
     */
    public void setCategoryId(Byte categoryId) {
        this.categoryId = categoryId;
    }
}